# Generated by Django 3.0.8 on 2020-08-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=50)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(max_length=20)),
                ('winner', models.IntegerField()),
                ('comment', models.TextField()),
                ('uuid', models.CharField(max_length=36)),
            ],
        ),
    ]
