# Generated by Django 3.1 on 2020-08-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50)),
                ('url_params', models.TextField()),
                ('date_played', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gamestatistic',
            name='name',
            field=models.TextField(default='Anonymous'),
            preserve_default=False,
        ),
    ]
